### ISSUE TITLE
64节遛狗, 慢慢来

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#815]
![smile-34 gif](https://cloud.githubusercontent.com/assets/2461165/15784314/9103ff70-29e4-11e6-85c6-0fd91a57412c.gif) Bravo!
![333](https://cloud.githubusercontent.com/assets/2461165/15797968/4dff93a2-2a5b-11e6-92d1-23a712f40485.png)

新狗现在的稳定性, 简直邪恶.

**Comment by panpeach** [comment]
老狗不减当年勇……
![6](https://cloud.githubusercontent.com/assets/13916352/15786247/413a3b12-29ee-11e6-86ef-c501610adb84.png)

**Comment by jasonliul** [comment]
@panpeach 

过节, 墙监居然都懒得宰杀ip祭祖了.
看来俺们遛狗族, 当下种群数量锐减, 成了珍惜濒危保护对象.
LOL

**Comment by lifly** [comment]
低调 低调 低调

**Comment by masktao** [comment]
现在的版本太棒了,把youtube的视频缓存调节到最大,直接缓存到底,感谢作者的每天努力
![image](https://cloud.githubusercontent.com/assets/13614353/15796497/500f4ffe-2a31-11e6-8c42-8eda7a6d7f3a.png)

**Comment by jasonliul** [comment]
@phuslu 
社长也得出来秀秀, 挥舞一下熊掌, 致意

社长: 狗友们好~
众: 社长好~

社长: 狗友们辛苦喇~
众: 为狗民服务~

**Comment by phuslu** [comment]
抬举了。与诸位结个善缘而已。

**Comment by cnshinchan** [comment]
今天正常使用，感谢社长。

**Comment by sishentibu** [comment]
今天竟然看到10M，不知道是换到联通，还是更改dns的缘故
最近的版本都不错，ip放的多，也不用经常换ip了

**Comment by jzp820927** [comment]
@masktao 怎么调节 youtube 视频缓存？
不会只有我一个人的电信网，不管用什么IP，速度都不会超过 200 kbps 吗？

**Comment by jasonliul** [comment]
@phuslu 
原来社长是佛徒. :)

须是操存涵养, 定云止水中,有## **狼奔狗跃**的景象,才见处一化齐之妙。

**Comment by drg78rnvgh** [comment]
@jzp820927  他说的还是goa时代的autorange吧，是不是bufsize

**Comment by jzp820927** [comment]
不太清楚，现在版本的 goproxy，不是已经取消了 youtub 的autorange 吗，site 里面都没有 googlevideo 了，莫非你们都在用 googlevideo autorange

**Comment by Lynchie** [comment]
应该是油猴脚本吧，youtube center？

**Comment by jzp820927** [comment]
等高手揭晓答案。

**Comment by masktao** [comment]
@jzp820927 chrome浏览器配YouTube Center扩展,取消dash,启动自定义缓存
![image](https://cloud.githubusercontent.com/assets/13614353/15798723/8d117ee2-2a75-11e6-944f-994300ea0c27.png)

**Comment by jzp820927** [comment]
我去，你定义这个缓存不是有 1TB 吧

**Comment by masktao** [comment]
@jzp820927 实际上,自定义缓存必须关闭DASH,但这个功能失效了,截图看出DASH是开启的,关键还是出口网速快ip快

**Comment by jzp820927** [comment]
@masktao 看你截图中的 动态码流播放(DASH)，后面框上空白的，应该是没开启状态吧？开启的话，后面应该有个勾吧？

**Comment by masktao** [comment]
DASH貌似无法关闭,截图中也是开启的,虽然选择了关闭.看了看说明,youtube 480p-1080p都无法关闭,貌似
DASH Playback

DASH Playback is a method on how a video should be buffered. If DASH Playback is enabled it will buffer the video in blocks. That means that every time you seek in the video it will have to rebuffer that block and it will not buffer the next block if you're not at the very end of the current block. If DASH Playback is turned off YouTube will load normally where you can pause the video and it will buffer to the end of the video and you can jump around in the video as much as you like.

YouTube's default option has DASH enabled, because it's buffering faster for people with a good internet connection. YouTube Center also have DASH Playback enabled by default.

Read more about DASH on Wikipedia

Please note that by disabling DASH Playback will result in 480p and 1080p not being available. This is because of a recent YouTube change.

**Comment by masktao** [comment]
DASH貌似无法关闭,截图中也是开启的,虽然选择了关闭.看了看说明,youtube 480p-1080p都无法关闭,貌似.但是使用youtube plus扩展又可以关闭这个选项
DASH Playback

DASH Playback is a method on how a video should be buffered. If DASH Playback is enabled it will buffer the video in blocks. That means that every time you seek in the video it will have to rebuffer that block and it will not buffer the next block if you're not at the very end of the current block. If DASH Playback is turned off YouTube will load normally where you can pause the video and it will buffer to the end of the video and you can jump around in the video as much as you like.

YouTube's default option has DASH enabled, because it's buffering faster for people with a good internet connection. YouTube Center also have DASH Playback enabled by default.

Read more about DASH on Wikipedia

Please note that by disabling DASH Playback will result in 480p and 1080p not being available. This is because of a recent YouTube change.

**Comment by masktao** [comment]
DASH貌似无法关闭,截图中也是开启的,虽然选择了关闭.看了看说明,youtube 480p-1080p都无法关闭,貌似.但是使用youtube plus扩展又可以关闭这个选项
youtube center的说明
DASH Playback

DASH Playback is a method on how a video should be buffered. If DASH Playback is enabled it will buffer the video in blocks. That means that every time you seek in the video it will have to rebuffer that block and it will not buffer the next block if you're not at the very end of the current block. If DASH Playback is turned off YouTube will load normally where you can pause the video and it will buffer to the end of the video and you can jump around in the video as much as you like.

YouTube's default option has DASH enabled, because it's buffering faster for people with a good internet connection. YouTube Center also have DASH Playback enabled by default.

Read more about DASH on Wikipedia

Please note that by disabling DASH Playback will result in 480p and 1080p not being available. This is because of a recent YouTube change.

youtube plus的说明
DASH (Dynamic Adaptive Streaming over HTTP) playback will be disabled, allowing YouTube to buffer videos without stopping, but the only available quality options with DASH disabled are 720p and below with no 60fps.
Constant buffering no longer works in Chrome.

**Comment by TangBaohua** [comment]
又到了64翻墙节了
